### ISSUE TITLE
{#example-echo-server} Use of async_write_some might lead to dropped data

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#104]
<a href="https://github.com/lewissbaker"><img src="https://avatars.githubusercontent.com/u/211814?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lewissbaker](https://github.com/lewissbaker)**
_Wednesday Dec 29, 2021 at 01:12 GMT_
_Originally opened as https://github.com/NVIDIA/stdexec/issues/344_

----

The echo server snippet shown in the paper issues an async_read_some() that reads up to the buffer-size number of bytes, but might read less. It then issues an `async_write_some()` to write those bytes to the output socket. However, it doesn't handle the case where `async_write_some()` might write fewer than `n` bytes. It should really have a nested loop around the `async_write_some()`, or potentially just use an `async_write()` that abstracts the loop around `async_write_some()`.

**Comment by lewissbaker** [comment]
Since this is just for updating an example and the paper has now been accepted, we are unlikely to fix the non-wording parts of the paper.
So closing this as won't-fix.
