### ISSUE TITLE
[execution.schedulers.queries.execute_may_block_caller] Missing design rationale

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#105]
<a href="https://github.com/lewissbaker"><img src="https://avatars.githubusercontent.com/u/211814?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lewissbaker](https://github.com/lewissbaker)**
_Wednesday Dec 29, 2021 at 10:44 GMT_
_Originally opened as https://github.com/NVIDIA/stdexec/issues/348_

----

The `this_thread::execute_may_block_caller()` CPO is added by P2300 but there is no design discussion of this customisation point that motivates its addition, explains its purpose or how it is intended to be used.

Can we add some discussion for this method?

**Comment by lewissbaker** [comment]
The `execute()` function and the corresponding query `execute_may_block_caller` have both been removed in P2300R10. Closing.
