### ISSUE TITLE
Do we need wording to express pipe-ability of senders?

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#107]
<a href="https://github.com/lucteo"><img src="https://avatars.githubusercontent.com/u/9896706?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lucteo](https://github.com/lucteo)**
_Tuesday Jan 04, 2022 at 13:06 GMT_
_Originally opened as https://github.com/NVIDIA/stdexec/issues/359_

----

Section [4.13](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2300r3.html#design-pipeable) describes that most of the senders are pipeable. However, in the "Specification" sections the senders don't have wording about pipe-ability.

I believe we need wording for each sender algo (section 9) that is pipe-able to express this. At this point, I can't think of how a decent write-up would look like.

**Comment by ericniebler** [comment]
<a href="https://github.com/lucteo"><img src="https://avatars.githubusercontent.com/u/9896706?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lucteo](https://github.com/lucteo)**
_Tuesday Jan 04, 2022 at 13:14 GMT_

----

Also, section 4.13 is missing `schedule_from`; I assume this is not pipeable by design, as it has the sender as the second parameter.

**Comment by lewissbaker** [comment]
In P2300R10, the section `[exec.adapt.objects]` has a definition of "pipeable sender adaptor closure objects" and "pipeable sender adaptor objects".

The pipeable algorithms all explicitly mention that they are "pipeable sender adaptor objects".
