### ISSUE TITLE
Mark members of exposition-only classes as exposition-only

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#109]
<a href="https://github.com/ericniebler"><img src="https://avatars.githubusercontent.com/u/225757?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ericniebler](https://github.com/ericniebler)**
_Saturday Jan 15, 2022 at 06:03 GMT_
_Originally opened as https://github.com/NVIDIA/stdexec/issues/395_

----

From Jens:

 - 9.6.4.3. execution::just

The members of "just-sender" need to be marked
"// exposition only" if that's intended; I think you
can get at the just-sender type by doing "decltype(just())".

Probably likewise everywhere else.

**Comment by lewissbaker** [comment]
Looking through the current wording in P2300R10, most of the members seem to be marked `// exposition only` now.

There are a couple that we may want to double-check on:
- `default-impls` - the members `get-attrs`, `get-env`, `get-state`, `start` and `complete` are in  italic code-font, but are not explicitly marked "exposition only".
- In [exec.just] the `struct impls-for<decayed-type-of<just-cpo>>` struct does not have the `start` member in italics.
- In [exec.continues.on] the `struct impls-for<continues_on_t>` struct does not have the `get_attrs` member in italics.
- In  [exec.then] the `struct impls-for<decayed-typeof<then-cpo>>` struct does not have the `complete` member in italics. Similarly for [exec.bulk].
- In [exec.when.all] the exposition only make-state structure has a function-scope state-type structure that is returned. This structure has members `arrive` and `complete` which are in italic code-font but are not marked exposition-only.

There are also cases where some members are marked exposition-only but are not in italics code-font. Are they meant to be?

**Comment by ericniebler** [comment]
I have left a review with these fixes on cplusplus/draft#7114

> There are also cases where some members are marked exposition-only but are not in italics code-font. Are they meant to be?

yes. do you know where?

**Comment by lewissbaker** [comment]
A few examples:
- in when_all wording `struct make-state::operator()::state-type` has a bunch of exposition only members that are not italics
- in split wording `struct shared-state` has a bunch of exposition only members that are not italics.
- The `struct split-receiver` member `sh_state` is not italics
- The split wording `local-state` class has private members that are not italics
- The exec.let wording has a `receiver2` structure with  exposition only members that are not italics
- The exec.let wording for get-state returns a local struct type with exposition only members that are not italics

**Comment by lewissbaker** [comment]
From what I can tell from the merged [PR](https://github.com/cplusplus/draft/pull/7114), all of the issues listed above regarding improper exposition-only markup have been fixed.

Closing.
