### ISSUE TITLE
Typos/issues Section 8 (General utilities library)

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#110]
<a href="https://github.com/dietmarkuehl"><img src="https://avatars.githubusercontent.com/u/1319703?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dietmarkuehl](https://github.com/dietmarkuehl)**
_Sunday Jan 16, 2022 at 23:31 GMT_
_Originally opened as https://github.com/NVIDIA/stdexec/issues/398_

----

There are a number of issue with Section 8:

1. Some declarations in the synopsis have a mismatch between the name used in the template head and the function declaration: `Fn` vs. `Tag`.
2. There are numerous places where the `<` isn't HTML escaped and the explicit argument list is swallowed when formatted.
3. Some arguments to `std::forward` are plain missing.
4. The expression for the definition of `call-result-t` is a list of objects rather than a call expression.
5. There are some casts which are either unnecessary (`auto(tag)`) or should use `std::forward`. However, see next item.
6. The specification in 8.1.2 (`tag_invoke`) is too verbose. I think it can be expressed in terms of [customization.point.object] (whose reference is missing) and [defns.expression-equivalent] as is done for other customization point objects.

I'm fairly certain about all but the last part. For the last part it may be reasonable to get an opinion from other LWG members. I will add a PR shortly.

**Comment by ericniebler** [comment]
<a href="https://github.com/dietmarkuehl"><img src="https://avatars.githubusercontent.com/u/1319703?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dietmarkuehl](https://github.com/dietmarkuehl)**
_Sunday Jan 16, 2022 at 23:40 GMT_

----

I have created [PR 399](https://github.com/brycelelbach/wg21_p2300_std_execution/pull/399) to address the issues mentioned here.

Regarding Eric's comment on recommending an exact implementation: if an exact implementation should be suggested, I think it would best become a Note, e.g., to allow implementations to deviate if they have a better implementation like explicit compiler support. My [PR 399](https://github.com/brycelelbach/wg21_p2300_std_execution/pull/399) currently doesn't reflect the Note but can update it accordingly if you think that's the way to go.

**Comment by ericniebler** [comment]
<a href="https://github.com/villevoutilainen"><img src="https://avatars.githubusercontent.com/u/963599?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [villevoutilainen](https://github.com/villevoutilainen)**
_Sunday Jan 16, 2022 at 23:43 GMT_

----

> Regarding Eric's comment on recommending an exact implementation: if an exact implementation should be suggested, I think it would best become a Note, e.g., to allow implementations to deviate if they have a better implementation like explicit compiler support. 

Implementations are always allowed to "deviate" based on the as-if rule.

**Comment by ericniebler** [comment]
<a href="https://github.com/dietmarkuehl"><img src="https://avatars.githubusercontent.com/u/1319703?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dietmarkuehl](https://github.com/dietmarkuehl)**
_Sunday Jan 16, 2022 at 23:51 GMT_

----

I don't think this section will stay as is. At the very least, a note should be added to motivate why the exact implementation is given. ...and if the exact implementation is given, the casts need to go or it needs to be explicitly mentioned that this formulation is needed as well.

I have already mentioned that I'm not as confident about this particular change than about the others. My objective of this exercise is to streamline the LWG processing of this paper: unless it is of much better quality than nearly all papers we receive we will not manage to get through it for the C++23 time-frame.

**Comment by lewissbaker** [comment]
I'm pretty sure all of these points have either been addressed or are no longer relevant after 2+ years of LWG review.
Closing.
