### ISSUE TITLE
Add utility for emplace-constructing a non-movable type

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#114]
<a href="https://github.com/ericniebler"><img src="https://avatars.githubusercontent.com/u/225757?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ericniebler](https://github.com/ericniebler)**
_Tuesday Dec 14, 2021 at 17:33 GMT_
_Originally opened as https://github.com/NVIDIA/stdexec/issues/318_

----

Add this, per request from @villevoutilainen :

```c++
template <invocable _Fun>
struct some_damn_name {
  _Fun __fun; // exposition only
  invoke_result_t<_Fun> operator()() && noexcept(is_nothrow_invocable_v<_Fun>) {
    return move(__fun)();
  }
};
template <invocable _Fun>
some_damn_name(_Fun) -> some_damn_name<_Fun>;
```

This can be used to emplace-construct non-movable types (like, say, an operation state) into (say) an `optional`.

If we name things by what they _do_, this would be something like `convertible_to_result_of` (yuk!). IF we name it by what it's _for_, it would be something like `elide_copy_from`.

I kinda like `elide_copy_from`, but others are likely to have different opinions.

**Comment by ericniebler** [comment]
<a href="https://github.com/lewissbaker"><img src="https://avatars.githubusercontent.com/u/211814?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lewissbaker](https://github.com/lewissbaker)**
_Tuesday Dec 21, 2021 at 00:44 GMT_

----

I think that you want to define `some_damn_name::operator invoke_result_t<_Fun>()` rather than `some_damn_name::operator ()`.
The latter is just wrapping the callable into another callable rather than wrapping it into something that is convertible to the result type.

**Comment by lewissbaker** [comment]
Note that P2300R10 now has the exposition-only helper `emplace-from<Fun>` which is used in the specification of [exec.let].

There is also an independent proposal for a facility like this called `std::elide` in [P3288R0](https://wg21.link/P3288R0).

I don't think we need to do anything else specific for std::execution specification. Closing.
