### ISSUE TITLE
scheduler concept should require that move-constructor does not exit with an exception

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#116]
<a href="https://github.com/whatishappened"><img src="https://avatars.githubusercontent.com/u/94090917?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [whatishappened](https://github.com/whatishappened)**
_Sunday Nov 28, 2021 at 11:03 GMT_
_Originally opened as https://github.com/NVIDIA/stdexec/issues/283_

----

>2. None of a scheduler’s copy constructor, destructor, equality comparison, or swap member functions shall exit via an exception.

1. `scheduler` concept requires the type to be `std::copy_constructible` which subsumes `std::move_constructible`. Scheduler is additionally required to not throw in copy constructor. Why is nothrow only required to copy constructor but not move constructor?  
2. `std::copy_constructible` subsumes `std::destructible` which requires the destructor to be `noexcept`. Requiring destructor to not throw there might be redundant.

**Comment by lewissbaker** [comment]
It seems that as of P2300R10, the issue of p3 not requiring the move-constructor to not exit with an exception still stands.

[exec.sched] p3 contains:
> None of a scheduler’s copy constructor, destructor, equality comparison, or swap member functions shall exit via an exception.

I think this should be changed:
```diff
-None of a scheduler’s copy constructor, destructor, equality comparison, or swap member functions shall exit via an exception.
+None of a scheduler’s move constructor, copy constructor, destructor, equality comparison, or swap member functions shall exit via an exception.
```

**Comment by lewissbaker** [comment]
A resolution to this issue has been proposed in https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2024/p3396r0.html

**Comment by lewissbaker** [comment]
The proposed resolution was adopted at the Wroclaw meeting.
See https://wg21.link/P3396R1
