### ISSUE TITLE
Default implementation of sender adaptors are underconstrained

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#118]
<a href="https://github.com/whatishappened"><img src="https://avatars.githubusercontent.com/u/94090917?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [whatishappened](https://github.com/whatishappened)**
_Sunday Nov 14, 2021 at 10:02 GMT_
_Originally opened as https://github.com/NVIDIA/stdexec/issues/258_

----

There are lots of sender adaptors that has to store the arguments in it, such as then, upon_, let_, bulk, etc.

Sender concept requires the type to be move constructible, so I believe any sensible implementation of those adaptors will require the arguments to be move constructible as well, however none of the specification of the default implementation of those adaptors constrains the arguments to be move constructible.

**Comment by lewissbaker** [comment]
In P2300R10 the algorithms `let_value/error/stopped`, `then/upon_error/upon_stopped`, `bulk` and `just/just_error` now all require their captured values/function-objects to satisfy `movable-value`, which implies move-constructibility.

So I think this issue is addressed now.
