### ISSUE TITLE
Consider removing `start_detached`

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#124]
<a href="https://github.com/brycelelbach"><img src="https://avatars.githubusercontent.com/u/398194?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [brycelelbach](https://github.com/brycelelbach)**
_Tuesday Oct 19, 2021 at 19:11 GMT_
_Originally opened as https://github.com/NVIDIA/stdexec/issues/217_

----

From @LeeHowes:

> If we have a reasonable async_scope definition, then [`start_detached`] fall[s] out more safely that way.

**Comment by lewissbaker** [comment]
The `start_detached()` algorithm was removed in P2300R10.

Removal was proposed in [P3187R1](https://wg21.link/P3187R1).

The alternative async-scope facility is being proposed by [P3149](https://wg21.link/P3149)
