### ISSUE TITLE
Consider removing `execute`

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#125]
<a href="https://github.com/brycelelbach"><img src="https://avatars.githubusercontent.com/u/398194?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [brycelelbach](https://github.com/brycelelbach)**
_Tuesday Oct 19, 2021 at 17:23 GMT_
_Originally opened as https://github.com/NVIDIA/stdexec/issues/216_

----

None

**Comment by lewissbaker** [comment]
The `execute()` algorithm was removed in P2300R10.

Removal was proposed in [P3187R1](https://wg21.link/P3187R1).
