### ISSUE TITLE
Add a section that talks about forward progress delegation

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#137]
<a href="https://github.com/griwes"><img src="https://avatars.githubusercontent.com/u/755021?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [griwes](https://github.com/griwes)**
_Saturday Jul 03, 2021 at 04:33 GMT_
_Originally opened as https://github.com/NVIDIA/stdexec/issues/146_

----

As mentioned by @ogiroux when we chatted about the words in #141, we should probably have a more central section about forward progress guarantees and how boost blocking and sync_wait relate to those.

**Comment by lewissbaker** [comment]
There is now a paragraph in `[exec.sync.wait]` p7 that talks about forward-progress delegation in terms of driving the `run_loop` scheduler.

> The behavior of this_thread::sync_wait(sndr) is undefined unless:
>
>    It blocks the current thread of execution ([defns.block]) with forward progress guarantee delegation ([intro.progress]) until the specified sender completes. [Note: The default implementation of `sync_wait` achieves forward progress guarantee delegation by providing a `run_loop` scheduler via the `get_delegation_scheduler` query on the sync-wait-receiver’s environment. The run_loop is driven by the current thread of execution. - end note]
