### ISSUE TITLE
How does diverging execution interact with algorithm customization?

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#141]
Say a sender has different completion schedulers for value and error completions. Questions:

* Does such a thing even satisfy the `sender` concept?
* If so, is it an error to apply a customizable algorithm to it?
* If not, what should happen?

**Comment by lewissbaker** [comment]
@ericniebler Is this issue resolved now?

P2300R10 contains `get_completion_scheduler<completion-tag>()` - is this sufficient to allow querying for different completion-schedulers for different completion-signals?

The wording for `completion-domain` helper seems to say that it is ill-formed to ask for the completion-domain of a sender that does not have a common-type for the completion-schedulers for set_value/set_error/set_stopped.

**Comment by ericniebler** [comment]
i think what's currently in P2300R10 is the best we can do here. closing.
