### ISSUE TITLE
Rewrite the algorithm specifications in terms of the exposition-only _`basic-sender`_ utility

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#142]
Follow the example of the [`then`/`upon_error`/`upon_stopped`](https://cplusplus.github.io/sender-receiver/execution.html#spec-execution.senders.adaptor.then) algorithms, the specifications of which have been tightened up by expressing them in terms of the [_`basic-sender`_](https://cplusplus.github.io/sender-receiver/execution.html#spec-execution.senders.general) exposition-only class and its assorted helpers.

- [x] #143
- [x] #144
- [x] #145
- [x] #146
- [x] #147
- [x] #148
- [ ] #149
- [ ] #150
- [x] ~~#151~~
- [x] ~~#152~~
- [x] ~~#153~~
- [x] #156
- [x] #158

**Comment by lewissbaker** [comment]
This has now been done.
