### ISSUE TITLE
stoppable_token concept definition redundantly rqeuires move_constructible

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#15]
<a href="https://github.com/lewissbaker"><img src="https://avatars.githubusercontent.com/u/211814?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lewissbaker](https://github.com/lewissbaker)**
_Tuesday Nov 15, 2022 at 01:12 GMT_
_Originally opened as https://github.com/brycelelbach/wg21_p2300_execution/issues/7_

----

`stoppable_token` definition in R5 requires both `move_constructible` and `copy_constructible`, however `copy_constructible` already implies `move_constructible` and so requiring `move_constructible` is redundant and should be removed.

**Comment by inbal2l** [comment]
@lewissbaker I believe this is fixed on the latest draft, as `stoppable_token` now requires `copyable`.
https://cplusplus.github.io/sender-receiver/execution.html#spec-stoptoken.concepts

**Comment by ericniebler** [comment]
fixed
