### ISSUE TITLE
Intro section for `[thread.stoptoken.concepts]` should be slimmed down

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#16]
<a href="https://github.com/lewissbaker"><img src="https://avatars.githubusercontent.com/u/211814?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lewissbaker](https://github.com/lewissbaker)**
_Tuesday Nov 15, 2022 at 01:16 GMT_
_Originally opened as https://github.com/brycelelbach/wg21_p2300_execution/issues/8_

----

The introduction paragraph for the `stoppable_token` concept has several sentences which are basically just duplicating information that can already be inferred from the concept definition.

> The `stoppable_token` concept checks for the basic interface of a “stop token” which is copyable and allows polling to see if stop has been requested and also whether a stop request is possible. It also requires an associated nested template-type-alias, T::callback_type<CB>, that identifies the stop-callback type to use to register a callback to be executed if a stop-request is ever made on a stoppable_token of type, T. The stoppable_token_for concept checks for a stop token type compatible with a given callback type. The unstoppable_token concept checks for a stop token type that does not allow stopping.

LWG suggested trying to slim down this intro paragraph.

**Comment by inbal2l** [comment]
@lewissbaker - this seems to be fixed on the latest draft, isn't it?
https://cplusplus.github.io/sender-receiver/execution.html#spec-stoptoken.concepts

**Comment by lewissbaker** [comment]
Yes, I think we can close this now.
The opening paragraph is slimmer, and LWG seems to have been happy with it.
