### ISSUE TITLE
P2300 LWG 2024/02/07 review

### ISSUE THREAD

**Issue by mhoemmen** [cplusplus/sender-receiver#185]
`shared_ptr` has language saying that the deletes are globally visible.  This implies a particular strength of atomic update for decrements.  (Lewis has a suggestion on PR #173.)  _`inc-ref`_ definition is good.

para 8: `Sndr` template parameter of _`shared-wrapper`_ needs disambiguation from the text's `Sndr` type.  (They aren't even the same type.)  We can remove `Sndr` from the text and leave the template parameter as-is, by using `decltype` etc. in the text.

_`shared-wrapper`_ needs a Note to explain lack of assignability and the two cases? or split the copy assignment.  The latter would make it clear that the move assignment is always allowed for both tag types, but the copy is not.  We want to split the assignment into move assignment and copy assignment.  Right now, it's doing double duty.

**Comment by jwakely** [comment]
The suggestion for _shared-wrapper_ is to split the assignment op into an unconstrained move assignment and a constrained copy assignment:

```c++
  shared-wrapper& operator=(shared-wrapper&& other) noexcept {
    other.sh_state.swap(sh_state);
    return *this;
  }
  shared-wrapper& operator=(const shared-wrapper& other) noexcept 
  requires same_as<Tag, split_t>
  {
    other.sh_state.swap(sh_state);
    return *this;
  }
```

**Comment by mhoemmen** [comment]
"to the following lambda" -> "to the following lambda expression" (9.1, specialization of _`impls-for`_ for _`shared-impl-tag`_)

**Comment by mhoemmen** [comment]
Reading and writing `state.sh_state->head`?  Need a release-acquire pair, not just relaxed.

**Comment by lewissbaker** [comment]
@ericniebler were all of these changes/suggestions applied?

**Comment by ericniebler** [comment]
They were.
