### ISSUE TITLE
provide allocator for algorithms that allocate

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#190]

**Comment by ericniebler** [comment]
...and does the allocator effect the sender's destructure-ing?

**Comment by ericniebler** [comment]
See also #46

**Comment by lewissbaker** [comment]
The `async_scope` paper [P3149](https://wg21.link/P3149) is currently looking at adding allocation customization for spawn/spawn_future algorithms.

Allocator customization for the `split()` algorithm should be addressed in #263.

The only other place in P2300 that I can see that allocates memory is the exposition-only `connect-awaitable` function, which has an implicit allocation in the coroutine-frame.

Do we want this to use the receiver's environment's allocator to allocate the coroutine-frame here?
CC: @ericniebler

**Comment by lewissbaker** [comment]
I have captured the allocation customization for coroutine-frames allocated by `connect-awaitable` helper into #268.

Closing this issue as all allocating functions are now tracked by other issues.
