### ISSUE TITLE
change the `on` algorithm to restore the starting execution context

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#192]

**Comment by ericniebler** [comment]
![image](https://github.com/cplusplus/sender-receiver/assets/225757/9a961af2-3455-4071-9a79-9e366254136f)

**Comment by ericniebler** [comment]
https://wg21.link/P3175R0

**Comment by lewissbaker** [comment]
This has now been adopted and merged into P2300R10.
We now have: `starts_on()`, `continues_on()` and `on()`.
