### ISSUE TITLE
Seems like there's a typo in P2300R9

### ISSUE THREAD

**Issue by Runner-2019** [cplusplus/sender-receiver#217]
<img width="957" alt="image" src="https://github.com/cplusplus/sender-receiver/assets/59395781/f2265c9c-3000-4f17-b247-22d540db31af">

**Comment by isidorostsa** [comment]
Also looks like in line 5308: R1(Args&&...) should be R1(Args**1**&&...): https://github.com/cplusplus/sender-receiver/blob/a50475d90b2aff5175b39e7f6866464c6dc8bf21/execution.bs#L5306-L5308
