### ISSUE TITLE
`get_completion_signatures()` doesn't take into account `transform_sender()` customizations

### ISSUE THREAD

**Issue by lewissbaker** [cplusplus/sender-receiver#227]
The current specification of `std::execution::get_completion_signatures(sndr, env)` just returns type of `sndr.get_completion_signatures(env)`.

However, this doesn't seem to take into account that when the env contains a domain that customises a sender's operation that it might return different sets of signatures. e.g. a different error type, might not be stoppable, etc.

Should the `std::execution::get_completion_signatures()` helper be applying the same `transform_sender()` transforms and then calling `sndr.get_completion_signatures()` on the result of `transform_sender()` instead?

**Comment by ericniebler** [comment]
OMG, and `connect` isn't using `transform_sender` either. This is a major oversight. Those changes were never actually proposed by P2999. /facepalm

**Comment by inbal2l** [comment]
@lewissbaker should this be closed as we have https://github.com/cplusplus/sender-receiver/issues/246?

**Comment by lewissbaker** [comment]
Yes, I believe this is now addressed by [P3303R0](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2024/p3303r0.html), which was merged into P2300R10.
