### ISSUE TITLE
Specification of `let_value`, etc. should not use inheritance in definition of `receiver2`

### ISSUE THREAD

**Issue by lewissbaker** [cplusplus/sender-receiver#230]
The current wording of `let_value`, `let_error`, `let_stopped` defines an exposition-only `receiver2` type that is defined to inherit from the user-provided `Rcvr` connected to the `let_xxx` sender.

This specification will not work for receiver types that are marked `final`.

We should instead store the parent operation's receiver in the parent operation state and forward completion-signalling-calls to that receiver.

**Comment by lewissbaker** [comment]
See also #231

**Comment by ericniebler** [comment]
fixed in R10
