### ISSUE TITLE
types that privately inherit from `receiver_adaptor` ought to satisfy `receiver`

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#29]
<a href="https://github.com/ericniebler"><img src="https://avatars.githubusercontent.com/u/225757?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ericniebler](https://github.com/ericniebler)**
_Tuesday Jun 20, 2023 at 00:57 GMT_
_Originally opened as https://github.com/brycelelbach/wg21_p2300_execution/issues/42_

----

None

**Comment by inbal2l** [comment]
@lewissbaker - I think this is not relevant anymore as `receiver_adaptor` was removed in R9:
https://cplusplus.github.io/sender-receiver/execution.html#r9

**Comment by lewissbaker** [comment]
Agreed. Closing.
