### ISSUE TITLE
sender concepts for awaitable types

### ISSUE THREAD

**Issue by maikel** [cplusplus/sender-receiver#305]
I was making my own coroutine task `basic_task<Ret, Queries...>` which is an awaitable for promises that have an env that is queryable for all specified Queries...

The current spec defines the following two sender concepts

```cpp
template<class Sndr>
    concept enable-sender =                                     // exposition only
      is-sender<Sndr> ||
      is-awaitable<Sndr, env-promise<empty_env>>;               // [exec.awaitable]

  template<class Sndr>
    concept sender =
      bool(enable-sender<remove_cvref_t<Sndr>>) &&
      requires (const remove_cvref_t<Sndr>& sndr) {
        { get_env(sndr) } -> queryable;
      } &&
      move_constructible<remove_cvref_t<Sndr>> &&
      constructible_from<remove_cvref_t<Sndr>, Sndr>;

  template<class Sndr, class Env = empty_env>
    concept sender_in =
      sender<Sndr> &&
      queryable<Env> &&
      requires (Sndr&& sndr, Env&& env) {
        { get_completion_signatures(std::forward<Sndr>(sndr), std::forward<Env>(env)) }
          -> valid-completion-signatures;
      };
```

The current concepts require `basic_task<Ret, Queries...>` to be awaitable in `env-promise<empty_env>` which is too strict, IMHO.  Instead we could require for `sender_in`:

```cpp
  template<class Sndr, class Env = empty_env>
    concept sender_in =
     is-awaitable<Sndr, env-promise<Env>> ||
      sender<Sndr> &&
      queryable<Env> &&
      requires (Sndr&& sndr, Env&& env) {
        { get_completion_signatures(std::forward<Sndr>(sndr), std::forward<Env>(env)) }
          -> valid-completion-signatures;
      };
```

There are some places where we mandate input to satisfy the sender concept. The most used one is for `connect(sndr, rcvr)` expressions. The current spec states https://eel.is/c++draft/exec.snd#exec.connect-6

> The expression connect(sndr, rcvr) is expression-equivalent to:
> [(6.1)](https://eel.is/c++draft/exec.snd#exec.connect-6.1)
> new_sndr.connect(rcvr) if that expression is well-formed[.](https://eel.is/c++draft/exec.snd#exec.connect-6.1.sentence-1)
> Mandates: The type of the expression above satisfies [operation_state](https://eel.is/c++draft/exec.opstate.general#concept:operation_state)[.](https://eel.is/c++draft/exec.snd#exec.connect-6.1.sentence-2)
> [(6.2)](https://eel.is/c++draft/exec.snd#exec.connect-6.2)
> Otherwise, connect-awaitable(new_sndr, rcvr)[.](https://eel.is/c++draft/exec.snd#exec.connect-6.2.sentence-1)
> Mandates: `sender<Sndr>` && `receiver<Rcvr>` is true.

I would like to Mandate `receiver<Rcvr> && sender_in<Sndr, env_of_t<Rcvr>>`

Any thoughts?

**Comment by ericniebler** [comment]
a type that satisfies `sender_in` needs to satisfy `sender`. otherwise subsumption is broken.

> Why do we require awaitables to work with an empty env?

we don't, but we do require an opt-in to satisfy the `sender` concept. making your type awaitable with an empty environment is one way to opt in. if your awaitable requires an environment, you have two options:
1. give your awaitable type a nested `sender_concept` typedef, or
2. specialize `enable_sender` for your awaitable type.

the problem is that somewhere along the way, the `enable_sender` variable template was turned into an exposition-only _`enable-sender`_ concept. we should roll back that change.

**Comment by maikel** [comment]
Thank you for clarification!

**Comment by jwakely** [comment]
Created https://cplusplus.github.io/LWG/issue4202

**Comment by ericniebler** [comment]
I also sent a list of bugs to lwgchair to import, including one for this issue that has a proposed resolution.

https://github.com/cplusplus/sender-receiver/issues/306

**Comment by jwakely** [comment]
I don't think #306 was one of the ones you asked to be opened as an issue. I'll update LWG 4202 to include that proposed resolution.
