### ISSUE TITLE
in_place_stop_token copy constructor/assignment and destructor

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#34]
<a href="https://github.com/vasama"><img src="https://avatars.githubusercontent.com/u/17240397?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vasama](https://github.com/vasama)**
_Friday Nov 10, 2023 at 07:17 GMT_
_Originally opened as https://github.com/brycelelbach/wg21_p2300_execution/issues/55_

----

The wording for `in_place_stop_token` is missing copy constructor and copy assignment and contains a destructor the effects of which are not described.

The [reference implementation](https://github.com/NVIDIA/stdexec/blob/6f23dd5b1d523541ce28af32fc2603403ebd36ed/include/stdexec/stop_token.hpp#L158) for `in_place_stop_token` provides trivial copy, trivial destructor and *linear move*. This is clearly not according to the specification.

Assuming the intent is for `in_place_stop_token` to be trivially copyable, the special member functions for copying should be specified defaulted and the destructor removed.

**Comment by lewissbaker** [comment]
The specification seems to now have trivial copy/move/dtor operations.
See http://eel.is/c++draft/stoptoken.inplace.general#1
