### ISSUE TITLE
Investigate feasibility of replacing `tag_invoke` with ranges-like CPOs

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#49]
<a href="https://github.com/ericniebler"><img src="https://avatars.githubusercontent.com/u/225757?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ericniebler](https://github.com/ericniebler)**
_Friday Nov 18, 2022 at 20:36 GMT_
_Originally opened as https://github.com/NVIDIA/stdexec/issues/686_

----

Rather than having `Mine::my_cpo(args)` find its customizations by making an ADL call to `tag_invoke(Mine::my_cpo, args)`, look into having the customization be found with `my_cpo(Mine::my_cpo, args)`. This would avoid the scaling issues of `tag_invoke`.

The tricky part is making sure that arbitrary queries can be forwarded in this scheme. This can be done if queries provide a CRTP base that does the forwarding for you.

The following gist demonstrates the technique:
https://gist.github.com/ericniebler/8e07f57a50d4de989d26bf15159a4730

In light of the fact that we're unlikely to get language support for customization points in C++26, it's important (IMO) to find a scalable replacement for `tag_invoke`.

**Comment by inbal2l** [comment]
@lewissbaker - can this be closed as we have [P2855R1](https://wg21.link/P2855)?

**Comment by lewissbaker** [comment]
Yes, all mention of `tag_invoke` has now been excised from P2300R10 wording.
Closing.
