### ISSUE TITLE
propose a `write` sender adaptor

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#56]
<a href="https://github.com/ericniebler"><img src="https://avatars.githubusercontent.com/u/225757?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ericniebler](https://github.com/ericniebler)**
_Tuesday Jul 19, 2022 at 22:31 GMT_
_Originally opened as https://github.com/NVIDIA/stdexec/issues/540_

----

This is the analogue of the `read` sender factory. `write` would adapt a sender by adding a set of [cpo, value] pairs to an environment.

**Proposed Usage:**

* `sndr | write(with(cpo1, value1), with(cpo2, value2)...)`

See also #538, #539

**Comment by ericniebler** [comment]
see also NVIDIA/stdexec#314

**Comment by inbal2l** [comment]
@ericniebler this is covered by "[P3284](https://wg21.link/P3284): finally, write_env, and unstoppable Sender Adaptors" correct?

**Comment by ericniebler** [comment]
it is
