### ISSUE TITLE
replace usages of "reference-qualified" with a yet-to-be-determined term

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#7]
https://github.com/cplusplus/sender-receiver/blob/a6fdb790fa40d37a170858c6c866c0199a11dfc2/execution.bs#L4025C12-L4025C12

**Comment by inbal2l** [comment]
@lewissbaker @ericniebler - I think this was replaced with "cvref-qualification" in one of LWG's reviews, but I may be misremembering it. In any case, the term "reference-qualified" does not appear in the latest draft (R10).

**Comment by lewissbaker** [comment]
Yes, I don't think this issue is relevant any more (or was already fixed) as "reference-qualified" term is no longer present in the wording.
