### ISSUE TITLE
Carve P2300 up into tiers to streamline wording review of the most important bits

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#85]
<a href="https://github.com/ericniebler"><img src="https://avatars.githubusercontent.com/u/225757?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ericniebler](https://github.com/ericniebler)**
_Saturday Feb 05, 2022 at 20:44 GMT_
_Originally opened as https://github.com/NVIDIA/stdexec/issues/454_

----

This is conditional on LEWG forwarding P2300 for C++23, which far from certain. If we must wait for '26 we can just leave P2300 as-is.

@griwes Do you want to try taking this one on?

**Comment by lewissbaker** [comment]
As P2300 has now been merged into the WD we can close this.
