### ISSUE TITLE
The `just_xxx` algorithms have non-`noexcept` `connect` functions

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#89]
<a href="https://github.com/anthonywilliams"><img src="https://avatars.githubusercontent.com/u/1382586?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anthonywilliams](https://github.com/anthonywilliams)**
_Thursday Feb 24, 2022 at 12:35 GMT_
_Originally opened as https://github.com/NVIDIA/stdexec/issues/473_

----

`just(42)` should not need to throw an exception when connecting any receiver, unless copying that receiver is not `noexcept`.

The `tag_invoke(connect_t,just-sender,some-receiver)` functions should be conditionally `noexcept`, so that if all the types involved are `nothrow_move_constructible` then `connect` is `noexcept`.

**Comment by lewissbaker** [comment]
I think that the intent of this issue is mostly addressed now in P2300R10.
However, there is still a wording bug that means it's not quite doing the right thing.

Closing this issue as it will be addressed by #279.
