### ISSUE TITLE
Algorithms such as `let_xxx` and `then` should propagate the environment from the connected receivers

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#90]
<a href="https://github.com/anthonywilliams"><img src="https://avatars.githubusercontent.com/u/1382586?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anthonywilliams](https://github.com/anthonywilliams)**
_Thursday Feb 24, 2022 at 17:22 GMT_
_Originally opened as https://github.com/NVIDIA/stdexec/issues/474_

----

As currently specified, the algorithms connect an internal receiver with the source sender, and then connect an internal sender with the supplied receiver. However, this disconnection between the source sender and the supplied receiver means that any parameters specified on the environment associated with the supplied receiver are not available to the source sender.
The internal receivers should be specified that the result of `execution::get_env(r)` on the internal receiver is the same as `execution::get_env(out_r)`

**Comment by lewissbaker** [comment]
I don't think it necessarily needs to be the same environment.
But you want to have `execution::get_env(r).query(x)` return the same result as `execution::get_env(out_r).query(x)`.

**Comment by lewissbaker** [comment]
The `let_value/error/stopped` algorithms now seem to be specified such that they pass a receiver to child operations that includes the result of queries from the environment of the receiver connected to the let_xxx sender. So I think the original issue is addressed now.

However, it also now passes to the second sender returned by the lambda an environment that has some modified properties (a get_scheduler query that is the completion scheduler of the predecessor, and a domain that is the domain of the completion scheduler, or alternatively a domain that is the same as the domain of the predecessor sender's domain).
