### ISSUE TITLE
`never_stop_token::stop_requested` and `never_stop_token::stop_possible` should be `[[nodiscard]]`

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#96]
<a href="https://github.com/hkaiser"><img src="https://avatars.githubusercontent.com/u/568063?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hkaiser](https://github.com/hkaiser)**
_Sunday Jan 23, 2022 at 23:48 GMT_
_Originally opened as https://github.com/NVIDIA/stdexec/issues/415_

----

... for consistency with `std::stop_­token`

**Comment by lewissbaker** [comment]
The current LEWG policy is to not have [[nodiscard]] on library specification and to let implementers put [[nodiscard]] as appropriate on methods they deem worthwhile.

Closing.
